test: don't fail on other tests if test_po fails
previously if this test failed, it would leave the current directory
in a inconstant state (pointing to a temporary directory that is
deleted).
This caused the following error on many tests in the testsuite:

cwd = os.getcwd()
OSError: [Errno 2] No such file or directory